import { readFile, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";

const root = new URL("../", import.meta.url);

export async function buildClient({ check = false } = {}) {
  const engine = await readFile(new URL("src/room-engine.mjs", root), "utf8");
  const boards = await readFile(new URL("src/board-resources.mjs", root), "utf8");
  const source = engine.replace(/^import \{ BOARD_GAME_SETS, BOARD_RESOURCES, BOARD_LAYOUTS \} from "\.\/board-resources.mjs";\n/m, boards + "\n")
    .replace(/^export \{ BOARD_GAME_SETS, BOARD_RESOURCES, BOARD_LAYOUTS \};\n/m, "");
  const exports = [...source.matchAll(/^export (?:function|class|const) (\w+)/gm)].map((match) => match[1]);
  const body = source.replace(/^import \{ randomInt, randomUUID \} from "node:crypto";\n/, "")
    .replace(/^export /gm, "");
  if (/^import /m.test(body)) throw new Error("The browser engine needs an explicit browser adapter for each import.");
  const random = `function randomUUID() { return root.crypto.randomUUID(); }
function randomInt(minimum, maximum) {
  if (maximum === undefined) { maximum = minimum; minimum = 0; }
  const range = maximum - minimum;
  const limit = Math.floor(4294967296 / range) * range;
  const bytes = new Uint32Array(1);
  do { root.crypto.getRandomValues(bytes); } while (bytes[0] >= limit);
  return minimum + bytes[0] % range;
}`;
  const packs = await Promise.all(["standard-54", "uno", "moon-outpost", "holdem-52"].map(async (id) =>
    JSON.parse(await readFile(new URL(`game-packs/${id}.json`, root), "utf8"))
  ));
  const outputs = new Map([
    ["public/tabletop-engine.js", `// Generated by scripts/build-client.mjs. Edit src/room-engine.mjs.\n(function(root) {\n"use strict";\n${random}\n${body}\nroot.ParlorEngine = Object.freeze({ ${exports.join(", ")} });\n})(globalThis);\n`],
    ["public/builtin-packs.js", `// Generated from game-packs/*.json.\n(function(root) { "use strict"; root.ParlorPacks = ${JSON.stringify(packs)}; })(globalThis);\n`]
  ]);
  for (const [path, text] of outputs) {
    const url = new URL(path, root);
    if (check) {
      const current = await readFile(url, "utf8").catch(() => "");
      if (current !== text) throw new Error(`${path} is stale. Run npm run build:client.`);
    } else await writeFile(url, text);
  }
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  await buildClient({ check: process.argv.includes("--check") });
  console.log(process.argv.includes("--check") ? "Shared browser engine is current." : "Shared browser engine and pack catalog built.");
}
